name: Python Package using Conda

on: 
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true

    - name: Create and Update Environment
      run: |
        conda env create --file environment.yml || conda env update --file environment.yml --name base
        conda activate base

    - name: Lint with flake8
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install -y pytest
        pytest

    - name: Save Conda Cache
      uses: actions/cache@v3
      with:
        path: ~/.conda/envs/base
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
